# Generated by Django 2.2 on 2021-04-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='phone number')),
                ('active', models.BooleanField(verbose_name='active')),
            ],
            options={
                'managed': True,
                'verbose_name': 'Client',
                'db_table': 'client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
