# Generated by Django 2.2 on 2021-04-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210420_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol')), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
