# Generated by Django 2.2 on 2021-04-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210423_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'permissions': (('Client | can_make_order', 'Can Make Order'),), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
