# Generated by Django 2.2 on 2021-04-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210423_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'permissions': (('can_make_order', 'Can Make Order'), ('can_active_client', 'Can Active Client')), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
